chore: small qol updates

diff --git a/bin/bin/zen-browser b/bin/bin/zen-browser
--- a/bin/bin/zen-browser
+++ b/bin/bin/zen-browser
@@ -1,4 +1,12 @@
 #!/usr/bin/bash
 [[ -z $MOZ_DISABLE_WAYLAND ]] && { [[ $XDG_CURRENT_DESKTOP == "GNOME" ]] && [[ -n $WAYLAND_DISPLAY ]] || [[ $XDG_SESSION_TYPE == "wayland" ]]; } && export MOZ_ENABLE_WAYLAND=1 && export MOZ_DBUS_REMOTE=1
-# exec /usr/lib/zen-browser/zen-bin "$@"
-exec /usr/bin/zen-browser "$@"
+
+# Try lib version first, fallback to bin version
+if [[ -x /usr/lib/zen-browser/zen-bin ]]; then
+    exec /usr/lib/zen-browser/zen-bin "$@"
+elif [[ -x /usr/bin/zen-browser ]]; then
+    exec /usr/bin/zen-browser "$@"
+else
+    echo "Error: zen-browser not found in /usr/lib/zen-browser/zen-bin or /usr/bin/zen-browser"
+    exit 1
+fi
